from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import enums
from datetime import datetime
from reportlab.platypus import Image
from reportlab.lib.units import inch
import io


def generate_pdf_report(mode, data):

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer)
    elements = []

    styles = getSampleStyleSheet()

    # ---------------- HEADER STYLE ----------------
    header_style = ParagraphStyle(
        name='HeaderStyle',
        parent=styles['Heading1'],
        alignment=enums.TA_CENTER,
        textColor=colors.white,
        backColor=colors.darkblue,
        spaceAfter=10
    )

    elements.append(Paragraph(
        " Real-Time Traffic Congestion Prediction",
        header_style
    ))
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(
        f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph(f"Report Type: {mode}", styles["Heading2"]))
    elements.append(Spacer(1, 0.3 * inch))

    # ---------------- SINGLE CITY ----------------
    if mode == "Single City Dashboard":

        # Congestion Badge Color
        if data["prediction"] == "High":
            badge_color = colors.red
        elif data["prediction"] == "Medium":
            badge_color = colors.orange
        else:
            badge_color = colors.green

        badge_style = ParagraphStyle(
            name='BadgeStyle',
            parent=styles['Normal'],
            backColor=badge_color,
            textColor=colors.white,
            alignment=enums.TA_CENTER
        )

        elements.append(Paragraph(
            f"Congestion Level: {data['prediction']}",
            badge_style
        ))
        elements.append(Spacer(1, 0.3 * inch))

        table_data = [
            ["Location", data["location"]],
            ["Current Speed", f"{data['current_speed']} km/h"],
            ["Free Flow Speed", f"{data['free_speed']} km/h"],
            ["Risk Score", f"{data['risk_score']} / 100"]
        ]

        table = Table(table_data, colWidths=[ 2.5 * inch, 4 * inch])

        table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ]))

        elements.append(table)

    # ---------------- MULTI CITY ----------------
    elif mode == "Multi City Comparison":

        table_data = [["City", "Speed", "Congestion", "Risk Score"]]

        for row in data:
            table_data.append([
                row["City"],
                str(row["Speed (km/h)"]),
                row["Congestion"],
                str(row["Risk Score"])
            ])

        table = Table(table_data)

        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))

        elements.append(table)

    # ---------------- HEATMAP ----------------
    elif mode == "India Heatmap":

        table_data = [["City", "Risk %"]]

        for row in data:
            table_data.append([row["City"], str(row["Risk %"])])

        table = Table(table_data)

        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.orange),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))

        elements.append(table)


    elements.append(Spacer(1, 0.6 * inch))
    elements.append(Paragraph(
        "<i>Generated by Real-Time Traffic Congestion System</i>",
        styles["Normal"]
    ))

    doc.build(elements)
    buffer.seek(0)

    return buffer